services:
  - type: web
    name: nyx-trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: MASTER_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MT5_LOGIN
        sync: false
      - key: MT5_PASSWORD
        sync: false
      - key: MT5_SERVER
        sync: false
      - key: AUTO_TRADING_ENABLED
        value: true